/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author User
 */
public class LaporanTransaksi extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form LaporanTransaksi
     */
    public LaporanTransaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connect();
    }

    private void Connect(){
        con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/kasir_restoran", "root", "");
        } catch(Exception e) {
            System.out.print("ERROR KONEKSI KE DATABASE:\n" + e);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        harian = new javax.swing.JButton();
        bulanan = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        harian.setBackground(new java.awt.Color(255, 204, 255));
        harian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        harian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/calendar (1).png"))); // NOI18N
        harian.setText("HARIAN");
        harian.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        harian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harianActionPerformed(evt);
            }
        });
        jPanel1.add(harian, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 140, 60));

        bulanan.setBackground(new java.awt.Color(255, 204, 255));
        bulanan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bulanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/calendar (1).png"))); // NOI18N
        bulanan.setText("BULANAN");
        bulanan.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulananActionPerformed(evt);
            }
        });
        jPanel1.add(bulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, 73));

        jComboBox1.setBackground(new java.awt.Color(255, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--BULAN--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 41));

        jComboBox2.setBackground(new java.awt.Color(255, 204, 255));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--TAHUN--", "2024", "2025", "2026", "2027", "2028" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 200, 41));

        jComboBox3.setBackground(new java.awt.Color(255, 204, 255));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--TAHUN--", "2024", "2025", "2026", "2027", "2028" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 210, 50));

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("LAPORAN PENDAPATAN BULANAN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel4)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 690, 60));

        jPanel5.setBackground(new java.awt.Color(255, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("LAPORAN PENDAPATAN HARIAN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconclose.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void harianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harianActionPerformed
        // TODO add your handling code here:
      try{
            String query = "SELECT tgl_byr, sum(total) as terjual FROM masterpesan JOIN detailpesan"
                    + " ON masterpesan.id_detail=detailpesan.id_detail where mid(tgl_byr, 6,2)="+jComboBox1.getSelectedItem()+" "
                    + "AND mid(tgl_byr, 1,4)="+jComboBox2.getSelectedItem()+" GROUP BY tgl_byr ORDER BY  DAY(tgl_byr);";
            JDBCCategoryDataset dataset=new JDBCCategoryDataset(con,query);
            JFreeChart chart=ChartFactory.createBarChart("Laporan Transaksi",  "Tanggal" , "total", dataset, PlotOrientation.VERTICAL, false,true,true);
            CategoryPlot categoryPlot=chart.getCategoryPlot();
            BarRenderer renderer=(BarRenderer) categoryPlot.getRenderer();
            chart.setBackgroundPaint(Color.PINK);
            chart.setBorderPaint(Color.PINK);
            categoryPlot.setBackgroundPaint(new Color (255,255,255));
            Color clr2=new Color(0, 153, 76);
            renderer.setSeriesPaint(0, clr2);

            CategoryPlot plot=null;
            renderer=new BarRenderer();

            ChartFrame frame=new ChartFrame("Laporan Transaksi",chart);

            frame.setVisible(true);
            frame.setSize(700,650);

        } catch (Exception e) {
            System.out.print("ERROR kueri KE DATABASE:\n" + e);
        }

                    
             
    }//GEN-LAST:event_harianActionPerformed

    private void bulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulananActionPerformed
        // TODO add your handling code here:
          try{
            String query = " SELECT date_format(tgl_byr,'%M')," +
"        sum(total) FROM masterpesan JOIN detailpesan"
                    + " ON masterpesan.id_detail=detailpesan.id_detail where mid(tgl_byr, 1,4)="+jComboBox3.getSelectedItem()+" GROUP BY date_format(tgl_byr,'%M') ORDER BY  MONTH(tgl_byr)  ;" ;
            JDBCCategoryDataset dataset=new JDBCCategoryDataset(con,query);
            JFreeChart chart=ChartFactory.createBarChart("Laporan Transaksi", "Tahun "+jComboBox3.getSelectedItem().toString(), "total", dataset, PlotOrientation.VERTICAL, false,true,true);
           CategoryPlot categoryPlot=chart.getCategoryPlot();
            BarRenderer renderer=(BarRenderer) categoryPlot.getRenderer();
            chart.setBackgroundPaint(Color.PINK);
            chart.setBorderPaint(Color.PINK);
            categoryPlot.setBackgroundPaint(new Color (255,255,255));
            Color clr2=new Color(0, 153, 76);
            renderer.setSeriesPaint(0, clr2);
            CategoryPlot plot=null;
            renderer=new BarRenderer();
            ChartFrame frame=new ChartFrame("Laporan Transaksi",chart);
            frame.setVisible(true);
            frame.setSize(700,650);

        } catch (Exception e) {
            System.out.print("ERROR query KE DATABASE:\n" + e);
        }
    }//GEN-LAST:event_bulananActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bulanan;
    private javax.swing.JButton harian;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
