/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class satuan extends javax.swing.JFrame {
Connection con;
    DefaultTableModel tm;
    private void connect (){
        con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/kasir_restoran","root","");
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n" + e);
        }
    }
    private void tampil_tabel(){
 tm = new DefaultTableModel(null,
    new Object[] {"ID SATUAN","NAMA SATUAN" });
    tbsatuan.setModel(tm);
    tm.getDataVector().removeAllElements();
    try {
        PreparedStatement s = con.prepareStatement("SELECT*FROM satuan");
        ResultSet r = s.executeQuery();
        while(r.next()){
        Object[] data ={ 
        r.getString(1),
        r.getString(2)
        };
        tm.addRow(data);
        }
 } catch(Exception e) {
 System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
 }
}
    /**
     * Creates new form satuan
     */
    public satuan() {
        initComponents();
        connect();
        tampil_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cr = new javax.swing.JTextField();
        idsat = new javax.swing.JTextField();
        namsat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsatuan = new javax.swing.JTable();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cr.setBackground(new java.awt.Color(255, 153, 102));
        cr.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cr.setForeground(new java.awt.Color(255, 255, 255));
        cr.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 300, 40));

        idsat.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(idsat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 260, 40));

        namsat.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(namsat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 260, 40));

        tbsatuan.setBackground(new java.awt.Color(255, 153, 102));
        tbsatuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbsatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsatuanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbsatuan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 710, 160));

        save.setBackground(new java.awt.Color(255, 153, 102));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Add.png"))); // NOI18N
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 110, 50));

        update.setBackground(new java.awt.Color(255, 153, 102));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Edit.png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 130, 40));

        delete.setBackground(new java.awt.Color(255, 153, 102));
        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Delete.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 130, 40));

        cari.setBackground(new java.awt.Color(255, 153, 102));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/find.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 120, 40));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 910, -1));

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kardus1.png"))); // NOI18N
        jLabel2.setText("DATA SATUAN");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconclose.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(289, 289, 289)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID SATUAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NAMA SATUAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 130, 20));

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kardus1.png"))); // NOI18N
        jLabel3.setText("DATA SATUAN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(335, 335, 335))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 910, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
       try {
    // Mengecek apakah satuan dengan ID atau nama yang sama sudah ada dalam database
    String query = "SELECT * FROM satuan WHERE id_satuan = ? OR nama_satuan = ?";
    PreparedStatement psCheck = con.prepareStatement(query);
    psCheck.setString(1, idsat.getText());
    psCheck.setString(2, namsat.getText());
    ResultSet rs = psCheck.executeQuery();
    
    if (rs.next()) {
        // Jika satuan sudah ada dalam database, tampilkan pesan kesalahan
        JOptionPane.showMessageDialog(this, "Satuan dengan ID atau nama yang sama sudah ada dalam database.");
    } else {
        // Jika satuan belum ada dalam database, lakukan operasi INSERT
        PreparedStatement ps = con.prepareStatement("INSERT INTO satuan VALUES (?,?)");
        ps.setString(1, idsat.getText());
        ps.setString(2, namsat.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data telah tersimpan");
        tampil_tabel();
    }
} catch(Exception e){
    JOptionPane.showMessageDialog(this, "Data gagal disimpan");
    System.out.println("Masukkan data dengan benar: " + e + "\n\n");
}

    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         try{
            PreparedStatement ps=con.prepareStatement("UPDATE satuan SET nama_satuan=? WHERE id_satuan=?");
            ps.setString(1, namsat.getText());
            ps.setString(2,  idsat.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data telah di updete");
            tampil_tabel();
        } catch(Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n" +e+ "\n\n");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         int ok=JOptionPane.showConfirmDialog(null, "Apakah anda yakin='" + idsat.getText() + "'", "Konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            try{
                PreparedStatement ps=con.prepareStatement("DELETE FROM satuan WHERE id_satuan=?");
                ps.setString(1, idsat.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data telah terHapus");
                tampil_tabel();
            } catch(Exception e){
                System.out.print("ERROR KUERI KE DATAABASE:\n" +e+ "\n\n");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
         tm = new DefaultTableModel (null,
        new Object[] {"id_satuan","nama_satuan"});
        tbsatuan.setModel(tm);
        tm.getDataVector().removeAllElements();
        try
        {
            PreparedStatement s=con.prepareStatement("SELECT * from satuan where nama_satuan LIKE '%"+cr.getText().toString()+"%'");
            ResultSet r=s.executeQuery();
            while(r.next())
            {
                Object[]data={
                r.getString(1),
                r.getString(2)};
                tm.addRow(data);
            }
            }
        catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
        }
    }//GEN-LAST:event_cariActionPerformed

    private void tbsatuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsatuanMouseClicked
        // TODO add your handling code here:
        int i=tbsatuan.getSelectedRow();
        if(i==-1){
            return;
        }
        String idsatuan=(String) tm.getValueAt(i, 0); 
        idsat.setText(idsatuan);
        String namasatuan=(String) tm.getValueAt(i, 1);
        namsat.setText(namasatuan); 
    }//GEN-LAST:event_tbsatuanMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(satuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(satuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(satuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(satuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new satuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JTextField cr;
    private javax.swing.JButton delete;
    private javax.swing.JTextField idsat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namsat;
    private javax.swing.JButton save;
    private javax.swing.JTable tbsatuan;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
